version: '3.1'
services:
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres